### ISSUE TITLE
Tools > Ebisu Error

### ISSUE THREAD

**Issue by LorenzDuremdes** [thetruejacob/memorize-anki#6]
I'm now getting this error when clicking "Tools > Ebisu" in Anki:

--

Error

An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.

If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.

When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.

Debug info:

Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2

Platform: Windows 10

Flags: frz=True ao=True sv=1

Add-ons, last update check: 2020-11-28 21:51:41

Caught exception:

Traceback (most recent call last):

File "C:\Users\PC-0000\AppData\Roaming\Anki2\addons21\Anki-Ebisu\__init__.py", line 125, in ebisuAll

card.flush()

File "C:\Users\PC-0000\AppData\Roaming\Anki2\addons21\Anki-Ebisu\__init__.py", line 73, in flush

reprocess(self)

File "C:\Users\PC-0000\AppData\Roaming\Anki2\addons21\Anki-Ebisu\__init__.py", line 46, in reprocess

card.type = CARD_REV

NameError: name 'CARD_REV' is not defined

**Comment by thetruejacob** [comment]
Just updated. Try again?
