### ISSUE TITLE
Error when selecting Again/Good and Tools > Ebisu (Anki 2.1.22)

### ISSUE THREAD

**Issue by MetalFir** [thetruejacob/memorize-anki#7]
**See comment below** 

 ****Tools > Ebisu:**** 

Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-28 15:45:19
Add-ons possibly involved: ⁨Anki-Ebisu-master⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 126, in ebisuAll
    card.flush()
  File "/Users/xxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 74, in flush
    reprocess(self)
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 41, in reprocess
    print(f"--------------\nCard {card.id} was last reviewed {fmtTimeSpan(secondsSinceLastReview)} ago. Its interval was {card.ivl}. Interval should be {fmtTimeSpan(ivlInSecond)}. I.e. in {fmtTimeSpan(remainingIntervalInSecond)}. ")
UnicodeEncodeError: 'ascii' codec can't encode character '\u2068' in position 52: ordinal not in range(128)

**selecting Again/Good in card:**

Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-28 15:45:19
Add-ons possibly involved: ⁨Anki-Ebisu-master, Pop-up Dictionary beta⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 31, in cmd
  File "aqt/webview.py", line 97, in _onCmd
  File "aqt/webview.py", line 500, in _onBridgeCmd
  File "</Applications/Anki 3.app/Contents/MacOS/decorator.pyc:decorator-gen-48>", line 2, in _linkHandler
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 663, in repl
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/153625306/main.py", line 240, in linkHandler
    return _old(self, url)
  File "aqt/reviewer.py", line 337, in _linkHandler
  File "</Applications/Anki 3.app/Contents/MacOS/decorator.pyc:decorator-gen-88>", line 2, in _answerCard
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 661, in repl
  File "aqt/reviewer.py", line 266, in _answerCard
  File "anki/schedv2.py", line 85, in answerCard
  File "/Users/xxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 81, in flushSched
    reprocess(self)
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 41, in reprocess
    print(f"--------------\nCard {card.id} was last reviewed {fmtTimeSpan(secondsSinceLastReview)} ago. Its interval was {card.ivl}. Interval should be {fmtTimeSpan(ivlInSecond)}. I.e. in {fmtTimeSpan(remainingIntervalInSecond)}. ")
UnicodeEncodeError: 'ascii' codec can't encode character '\u2068' in position 52: ordinal not in range(128)

**Comment by MetalFir** [comment]
When updating to the latest version of Anki (2.1.35) this error comes up when clicking Ebisu:

Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-28 15:45:19
Add-ons possibly involved: ⁨Anki-Ebisu-master⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 126, in ebisuAll
    card.flush()
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 74, in flush
    reprocess(self)
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 49, in reprocess
    card.due = self.today # TODO: find real day
NameError: name 'self' is not defined

**Comment by thetruejacob** [comment]
I added a patch. See if you still get this issue.

**Comment by MetalFir** [comment]
> I added a patch. See if you still get this issue.


Thank you, I think that did the trick. I get:

"Review Results are [False, True, False],
 Review Times are [datetime.datetime(2020, 11, 27, 23, 39, 42, 738000), datetime.datetime(2020, 11, 28, 1, 49, 13, 12000), datetime.datetime(2020, 11, 28, 19, 52, 22, 984000)],
 previousTime is 2020-11-27 23:39:42.738000,
 model is (3, 3, 24)"

I assume this is normal?

**Edit:**

**After I clicked further I got this error message...**

Caught exception:
Traceback (most recent call last):
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master-5/__init__.py", line 128, in ebisuAll
    card.flush()
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master-5/__init__.py", line 74, in flush
    reprocess(self)
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master-5/__init__.py", line 46, in reprocess
    card.type = CARD_REV
NameError: name 'CARD_REV' is not defined

**Comment by thetruejacob** [comment]
Ah, I forgot to turn those off. Let me fix that for you. Thank you so much for helping me test this out. It's going much quicker when there are more people spotting the bugs. Try pulling from the repo now.

**Comment by MetalFir** [comment]
> Ah, I forgot to turn those off. Let me fix that for you. Thank you so much for helping me test this out. It's going much quicker when there are more people spotting the bugs. Try pulling from the repo now.



People should be the one thanking you, for trying to improve on Anki's SM2 algorithm.👍



Unfortunately I now get this error after Tools > Ebisu:


Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-28 15:45:19
Add-ons possibly involved: ⁨Anki-Ebisu-master-6⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master-6/__init__.py", line 128, in ebisuAll
    card.flush()
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master-6/__init__.py", line 75, in flush
    oldFlush(self)
  File "anki/cards.py", line 89, in flush
TypeError: 123.27296731149771 has type float, but expected one of: int, long

**Comment by thetruejacob** [comment]
Okay, this problem I couldn't replicate. My hypothesis is that you're reviewing an overdue card (the next interval was actually in the past). I set it so that the solution is it will schedule these cards within 10 seconds. Could you check now? If I'm correct, there will be a popup indicating that the card was overdue. If you don't see the popup, then I was wrong.

**Comment by MetalFir** [comment]
> Okay, this problem I couldn't replicate. My hypothesis is that you're reviewing an overdue card (the next interval was actually in the past). I set it so that the solution is it will schedule these cards within 10 seconds. Could you check now? If I'm correct, there will be a popup indicating that the card was overdue. If you don't see the popup, then I was wrong.


 For Tools > Ebisu I get this message: 

**"This card is overdue. The next interval will be -10"**


then this error message:


Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-28 15:45:19
Add-ons possibly involved: ⁨Anki-Ebisu-master-7⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master-7/__init__.py", line 129, in ebisuAll
    card.flush()
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master-7/__init__.py", line 76, in flush
    oldFlush(self)
  File "anki/cards.py", line 89, in flush
ValueError: Value out of range: -10


**So I think you may be right** 

What do you advise I do?

**Comment by thetruejacob** [comment]
Ah, okay, I changed it to self.today. Let's see if this works now.

**Comment by MetalFir** [comment]
> Ah, okay, I changed it to self.today. Let's see if this works now.

Sorry Unfortunately you get this...

Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-29 16:14:06
Add-ons possibly involved: ⁨Anki-Ebisu-master

Caught exception:
Traceback (most recent call last):
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 126, in ebisuAll
    for cid in mw.col.db.list(f"SELECT id FROM cards where queue in ({QUEUE_LRN}, {QUEUE_DAY_LRN}, {QUEUE_REV})"):
NameError: name 'QUEUE_LRN' is not defined

**Comment by thetruejacob** [comment]
Got it. Forgot that one line there. Could you try it now?

**Comment by MetalFir** [comment]
After a message of "card interval 0"

Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-30 16:30:43
Add-ons possibly involved: ⁨Anki-Ebisu-master-

Caught exception:
Traceback (most recent call last):
  File "/Users/xxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 128, in ebisuAll
    card.flush()
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 74, in flush
    reprocess(self)
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 48, in reprocess
    card.ivl = self.today # set to something else? Originally card.ivl = ivlInHour
NameError: name 'self' is not defined

> Got it. Forgot that one line there. Could you try it now?

**Comment by thetruejacob** [comment]
Okay, made a change.

**Comment by MetalFir** [comment]
> Okay, made a change.


Caught exception:
Traceback (most recent call last):
  File "/Users/xxxxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 128, in ebisuAll
    card.flush()
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master/__init__.py", line 75, in flush
    oldFlush(self)
  File "anki/cards.py", line 89, in flush
TypeError: 17.488853047189004 has type float, but expected one of: int, long

similar to comment above:



> > Ah, I forgot to turn those off. Let me fix that for you. Thank you so much for helping me test this out. It's going much quicker when there are more people spotting the bugs. Try pulling from the repo now.
> 
> People should be the one thanking you, for trying to improve on Anki's SM2 algorithm.👍
> 
> Unfortunately I now get this error after Tools > Ebisu:
> 
> Debug info:
> Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
> Platform: Mac 10.16
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2020-11-28 15:45:19
> Add-ons possibly involved: ⁨Anki-Ebisu-master-6⁩
> 
> Caught exception:
> Traceback (most recent call last):
> File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master-6/**init**.py", line 128, in ebisuAll
> card.flush()
> File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/Anki-Ebisu-master-6/**init**.py", line 75, in flush
> oldFlush(self)
> File "anki/cards.py", line 89, in flush
> TypeError: 123.27296731149771 has type float, but expected one of: int, long

**Comment by thetruejacob** [comment]
This is weird, we're getting the same problem again. I'm going to need to ask for help from some other developers. Thanks a lot again. Do you mind reaching me on the anki discord? https://discord.gg/prcYRaAM

**Comment by thetruejacob** [comment]
@Arthur-Milchior Do you know what the issue might be?

**Comment by Arthur-Milchior** [comment]
Hi,

I've some free time during holiday, so I can look at add-ons now.
I assume the question is related only to the last error message.

If you look at rslib/backend.proto you'll see that Card takes only integral values and a string.  (In pylib/anki/rsbackend you'll see that BackendCard is protobuf's card format)

This mean that you tried to put a floating number instead of an integral number. I don't know exactly in which value you did that, because I only have got a line number, and this is the line of the constructor. I really believe this is a big problem and should be corrected in protobuf->python compiler, but that's another question (I may take a look at it, but I don't promise anything.)

I would have expected the problem to occur in `reprocess`, since it changes some card's value. However, all values assigned to the card are rounded, so it makes little sens.

My best guess at this point would be to try to change card's setter, so that it print update which occurs, and then you'll see what value is set to 123.27.... but that's not a simple job.

Really, unless you've changed the code since the bug was reported, I've no idea what's going on

**Comment by Arthur-Milchior** [comment]
I've just made a pull request to protobuf which, hopefully, would lead to more explicit error message, stating exactly which field was wrong.

But this won't solve this problem until this PR is accepted, merged in a new release, and the release used by anki, so it will takes month at least.
